// Open Azure Data Explorer and sign in with a personal Microsoft account.
// https://dataexplorer.azure.com/clusters/help/databases/SecurityLogs
// Select the SecurityLogs database from the left-pane navigation tree.
// Read descriptions, copy, and Run these queries in Data Explorer. 

// Shows all tables in the current database
.show tables 

// Selects the "AuthenticationEvents" table, provides a total count of events.
AuthenticationEvents
| count 

// Takes 5 random rows and all columns.
AuthenticationEvents
| take 5

// Takes 5 random rows and only the 3 specified columns.
AuthenticationEvents
| take 5
| project username, timestamp, result

// Takes 5 random rows and only the 1 specified (distinct) columns.
AuthenticationEvents
| take 5
| distinct username

// Filters by condition, showing failed logins for user 'chricks'
AuthenticationEvents
| where username == 'chricks' and result == 'Failed Login'


